import Head from "next/head";
// DATA
import data from "../api/cmd.json";
import { Footer } from "../components/Footer.component";
// COMPONENTS
import { Hero } from "../components/Hero.component";
import { InfoBox } from "../components/InfoBox.component";
import { PhotoBox } from "../components/PhotoBox.component";
import { PreFooter } from "../components/PreFooter.component";
// TYPES
import type { NextPage } from "next";

const Cmd: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CMD | Sarah Radtke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        img="cmd"
        title={data.heroTitle}
        text={data.heroText}
        center
        underline
      />
      <InfoBox headline={data.symptomTitle} list={data.symptomList} />
      <PhotoBox
        title={data.photoTitle}
        text={data.photoText}
        img="cmd2"
        underline
      />
      <PreFooter site="CMD" />
      <Footer />
    </div>
  );
};

export default Cmd;
