import Head from "next/head";
// COMPONENTS
import { TimeLine } from "../components/TimeLine";
import { PhotoBox } from "../components/PhotoBox.component";
import { InfoBox } from "../components/InfoBox.component";
import { PreFooter } from "../components/PreFooter.component";
import { Footer } from "../components/Footer.component";
// DATA
import data from "../api/aboutMe.json";
// TYPES
import type { NextPage } from "next";

const UeberMich: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Über Mich | Sarah Radtke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PhotoBox
        title={data.photoTitle}
        text={data.photoText}
        img="mittelpunkt"
        underline
      />
      <InfoBox text={data.symptomText} />
      <TimeLine vita={data.vita} />
      <PreFooter />
      <Footer />
    </div>
  );
};

export default UeberMich;
